name = "datasnake-io"
account_id = "47e13e9e668bc72035b71e7fbf068b39"
workers_dev = false
compatibility_date = "2024-02-19"

# Explicitly set the entry-point file
main = "./.output_datasnake/server/index.mjs"

compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "https://datasnake.io/*", zone_id = "cb4db41dda1c0d71ff09cb9638c4c376" }
]

[site]
bucket = ".output_datasnake/public"