name = "d1-worker"
main = "./d1-worker.js"
compatibility_date = "2024-12-08"

[[d1_databases]]
binding = "DB"
database_name = "auth-db"
database_id = "58440f24-cf60-4eda-84c8-a72ec6384fad"
preview_database_id = "bc15f714-a894-4df9-bce3-871b60251a5d" 

[env.preview]
name = "d1-worker-preview"
main = "./d1-worker.js"

[[env.preview.d1_databases]]
binding = "auth-deb"
database_name = "auth-db-preview"
database_id = "bc15f714-a894-4df9-bce3-871b60251a5d"