name = "d1-worker"
main = "./d1-worker.js"
compatibility_date = "2024-12-08"

[[d1_databases]]
binding = "auth_db"
database_name = "auth-db"
database_id = "1b6533fe-ca99-4509-9890-b7cb594f3d6a"
preview_database_id = "bc15f714-a894-4df9-bce3-871b60251a5d"

[env.preview]
name = "d1-worker-preview"

[[env.preview.d1_databases]]
binding = "auth_db"
database_name = "auth-db-preview"
database_id = "bc15f714-a894-4df9-bce3-871b60251a5d"

[env.production]
name = "d1-worker-production"

[[env.production.d1_databases]]
binding = "auth_db"
database_name = "auth-db"
database_id = "1b6533fe-ca99-4509-9890-b7cb594f3d6a"
